version: "3"
services:
#  nginx:
#    image: kirillamurskiy/otus-clouds-2019-09-hw3-nginx-reverseproxy:1.0.0
#    container_name: nginx-reverseproxy
#    restart: unless-stopped
#    ports:
#      - 5000:80
#    networks:
#      - mydotnetnetwork
  nginx:
    image: social/nginx
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - auth
      - users
    ports:
      - 5002:80
    networks:
      - socialnetwork
  
  auth:
    image: social/auth
    container_name: auth
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__UsersDb=${USERS_DB}
    restart: unless-stopped
 #   ports:
 #     - 5000:80
    depends_on:
      - users_db_migrator
    networks:
      - socialnetwork
  
  users:
    image: social/users
    container_name: users
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__UsersDb=${USERS_DB}
    restart: unless-stopped
 #   ports:
 #     - 5001:80
    depends_on:
      - users_db_migrator
    networks:
      - socialnetwork
  
  users_db_migrator:
    image: social/users-db-migrator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__UsersDb=${USERS_DB}
  
networks:
  socialnetwork:
    driver: bridge