POST http://localhost:5010/api/auth/register
Content-Type: application/json

{
  "email": "user7@example.com",
  "password": "string",
  "repeatedPassword": "string",
  "givenName": "Dich",
  "familyName": "Tristov",
  "age": 25,
  "city": "Vzdrochniy",
  "interests": "Drinking"
}

###

POST http://localhost:5010/api/auth/login?email=user6@example.com&password=string

###

DELETE http://localhost:5010/api/auth/token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMSIsIm5iZiI6MTU4MTAyNjgzOCwiZXhwIjoxNTgxMDMwNDM4LCJpc3MiOiJobC1zb2NpYWxuZXR3b3JrMSIsImF1ZCI6ImhsLXNvY2lhbG5ldHdvcmsifQ.-DvihHSsQsM9IWhVVJ_DnrSewjZwx--iHiQBBdzAuEA

###

GET http://localhost:5010/api/users/1

###

GET http://localhost:5010/api/users/count
Content-Type: application/json

{
  "city": "vzdrochniy",
  "givenName": "dich",
  "familyName": "tristov",
  "interests": "drinking",
  "maxAge": 25,
  "minAge": 25
}
###

GET http://localhost:5010/api/users?skip=0&take=10
Content-Type: application/json

{
  "city": "vzdrochniy",
  "givenName": "dich",
  "familyName": "tristov",
  "interests": "drinking",
  "maxAge": 25,
  "minAge": 25
}

###

PUT http://localhost:5010/api/users/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwibmJmIjoxNTgxMDkyMjc0LCJleHAiOjE1ODEwOTU4NzQsImlzcyI6ImhsLXNvY2lhbG5ldHdvcmsxIiwiYXVkIjoiaGwtc29jaWFsbmV0d29yayJ9.5pt59AfP7c90uItzdqItDLpo3STwqc_fIkFVQcGo32Q

{
  "email": "user6@example.com",
  "city": "Vzdrochniy1",
  "givenName": "Dich",
  "familyName": "Tristov",
  "interests": "Drinking",
  "Age": 26
}

###